@hostname = localhost
@port = 8080
@host = http://{{hostname}}:{{port}}


### 1. Registrar un nuevo estudiante con datos por defecto (ÉXITO - 201)
POST {{host}}/api/estudiantes/registro
Content-Type: application/json

{
  "username": "test8user",
  "password": "password",
  "email": "test8user@example.com"
}

### 2. Intentar registrar el mismo usuario (Error)
POST {{host}}/api/estudiantes/registro
Content-Type: application/json

{
  "username": "test6user",
  "password": "password",
  "email": "test6user@example.com"
}



### 3. Obtener todos los estudiantes (Verificar registro)
GET {{host}}/api/estudiantes
