-- Manual PostgreSQL objects not generated by Hibernate
-- Run this script manually after schema creation/update.

BEGIN;

CREATE EXTENSION IF NOT EXISTS citext;

CREATE OR REPLACE FUNCTION fn_set_fecha_actualizacion()
RETURNS TRIGGER AS $$
BEGIN
    NEW.fecha_actualizacion := NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF to_regclass('public.toma_materia') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_toma_materia_fecha_actualizacion ON toma_materia;
        CREATE TRIGGER trg_toma_materia_fecha_actualizacion
        BEFORE UPDATE ON toma_materia
        FOR EACH ROW
        EXECUTE FUNCTION fn_set_fecha_actualizacion();
    END IF;
END;
$$;

DO $$
BEGIN
    IF to_regclass('public.ofertas') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_ofertas_fecha_actualizacion ON ofertas;
        CREATE TRIGGER trg_ofertas_fecha_actualizacion
        BEFORE UPDATE ON ofertas
        FOR EACH ROW
        EXECUTE FUNCTION fn_set_fecha_actualizacion();
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validar_carrera_estudiante_malla()
RETURNS TRIGGER AS $$
DECLARE
    v_carrera_malla VARCHAR(120);
BEGIN
    SELECT carrera
    INTO v_carrera_malla
    FROM malla
    WHERE id = NEW.malla_id;

    IF v_carrera_malla IS NULL THEN
        RAISE EXCEPTION 'La malla % no existe.', NEW.malla_id;
    END IF;

    IF NEW.carrera <> v_carrera_malla THEN
        RAISE EXCEPTION
            'La carrera del estudiante (%) debe coincidir con la carrera de la malla (%).',
            NEW.carrera, v_carrera_malla;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF to_regclass('public.estudiante') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_validar_carrera_estudiante_malla ON estudiante;
        CREATE TRIGGER trg_validar_carrera_estudiante_malla
        BEFORE INSERT OR UPDATE OF carrera, malla_id ON estudiante
        FOR EACH ROW
        EXECUTE FUNCTION fn_validar_carrera_estudiante_malla();
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION fn_sincronizar_carrera_desde_malla()
RETURNS TRIGGER AS $$
BEGIN
    UPDATE estudiante
    SET carrera = NEW.carrera
    WHERE malla_id = NEW.id
      AND carrera IS DISTINCT FROM NEW.carrera;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF to_regclass('public.malla') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_sincronizar_carrera_desde_malla ON malla;
        CREATE TRIGGER trg_sincronizar_carrera_desde_malla
        AFTER UPDATE OF carrera ON malla
        FOR EACH ROW
        EXECUTE FUNCTION fn_sincronizar_carrera_desde_malla();
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION fn_validar_horario_json()
RETURNS TRIGGER AS $$
DECLARE
    v_bloque JSONB;
    v_dia    TEXT;
    v_inicio TEXT;
    v_fin    TEXT;
BEGIN
    IF jsonb_typeof(NEW.horario_json) <> 'array' THEN
        RAISE EXCEPTION 'horario_json debe ser un arreglo JSON.';
    END IF;

    FOR v_bloque IN
        SELECT value
        FROM jsonb_array_elements(NEW.horario_json)
    LOOP
        IF jsonb_typeof(v_bloque) <> 'object' THEN
            RAISE EXCEPTION 'Cada bloque de horario_json debe ser un objeto.';
        END IF;

        IF NOT (v_bloque ? 'dia' AND v_bloque ? 'inicio' AND v_bloque ? 'fin') THEN
            RAISE EXCEPTION 'Cada bloque de horario_json debe tener dia, inicio y fin.';
        END IF;

        v_dia := v_bloque->>'dia';
        v_inicio := v_bloque->>'inicio';
        v_fin := v_bloque->>'fin';

        IF v_dia NOT IN ('Lunes', 'Martes', 'Miercoles', 'Miércoles', 'Jueves', 'Viernes', 'Sabado', 'Sábado', 'Domingo') THEN
            RAISE EXCEPTION 'Día inválido en horario_json: %', v_dia;
        END IF;

        IF v_inicio !~ '^(?:[01]\d|2[0-3]):[0-5]\d$' THEN
            RAISE EXCEPTION 'Hora de inicio inválida en horario_json: %', v_inicio;
        END IF;

        IF v_fin !~ '^(?:[01]\d|2[0-3]):[0-5]\d$' THEN
            RAISE EXCEPTION 'Hora de fin inválida en horario_json: %', v_fin;
        END IF;

        IF v_inicio >= v_fin THEN
            RAISE EXCEPTION 'La hora de inicio (%) debe ser menor que la hora fin (%).', v_inicio, v_fin;
        END IF;
    END LOOP;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF to_regclass('public.ofertas') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_validar_horario_json_ofertas ON ofertas;
        CREATE TRIGGER trg_validar_horario_json_ofertas
        BEFORE INSERT OR UPDATE OF horario_json ON ofertas
        FOR EACH ROW
        EXECUTE FUNCTION fn_validar_horario_json();
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION fn_limpiar_horarios_otro_semestre()
RETURNS TRIGGER AS $$
BEGIN
    DELETE FROM horarios_recomendados
    WHERE estudiante_id = NEW.estudiante_id
      AND semestre <> NEW.semestre
      AND id <> NEW.id;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF to_regclass('public.horarios_recomendados') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_limpiar_horarios_otro_semestre ON horarios_recomendados;
        CREATE TRIGGER trg_limpiar_horarios_otro_semestre
        AFTER INSERT ON horarios_recomendados
        FOR EACH ROW
        EXECUTE FUNCTION fn_limpiar_horarios_otro_semestre();
    END IF;
END;
$$;

CREATE OR REPLACE FUNCTION fn_evitar_prerequisito_inverso_directo()
RETURNS TRIGGER AS $$
DECLARE
    v_existe BOOLEAN;
BEGIN
    SELECT EXISTS (
        SELECT 1
        FROM prerequisitos p
        WHERE p.id_materia = NEW.id_prerequisito
          AND p.id_prerequisito = NEW.id_materia
    )
    INTO v_existe;

    IF v_existe THEN
        RAISE EXCEPTION
            'No se permite prerequisito inverso directo entre materia % y materia %.',
            NEW.id_materia, NEW.id_prerequisito;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DO $$
BEGIN
    IF to_regclass('public.prerequisitos') IS NOT NULL THEN
        DROP TRIGGER IF EXISTS trg_evitar_prerequisito_inverso_directo ON prerequisitos;
        CREATE TRIGGER trg_evitar_prerequisito_inverso_directo
        BEFORE INSERT OR UPDATE OF id_materia, id_prerequisito ON prerequisitos
        FOR EACH ROW
        EXECUTE FUNCTION fn_evitar_prerequisito_inverso_directo();
    END IF;
END;
$$;

COMMIT;
