spring.datasource.url=${SPRING_DATASOURCE_URL:${DATABASE_URL}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.xxxxx}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:EasySchedule}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.show-sql=false